version: '2.2'
services:
  setlxplay:
    build: .
    restart: always
    ports:
    - "8004:80"
    volumes:
    - setlxCodeStorage:/root/db
    - ./www:/root/www
    cpu_percent: 50
    cpu_shares: 50
    mem_limit: 250m
    domainname: setlx.dotcookie.me
    hostname: setlxplayground
volumes:
  setlxCodeStorage: {}