version: '3'
services:
  setlxplay:
    build: .
    ports:
    - "8004:80"
    volumes:
    - setlxCodeStorage:/root/db
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
volumes:
  setlxCodeStorage: {}